name: school_management
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.2.1
  dropdown_search: ^5.0.6
  date_time_picker: ^2.1.0
  # date_field: ^3.0.5
  fzregex: ^2.0.0
  # firebase_core: ^2.24.2
  flutter_svg: ^2.0.9
  flare_flutter: ^3.0.2
  # randomizer: ^0.0.2
  flrx_validator: ^0.6.0
  http: ^1.1.2
  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  select_form_field: ^2.2.0
  url_launcher: ^6.2.2
  photo_view: ^0.14.0
  webview_flutter: ^4.4.2
  pdf: ^3.10.7
  async: ^2.11.0
  path: ^1.8.3
  # flutter_pdfview: ^1.3.2
  # flutter_downloader: ^1.11.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/notification.png
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
